update docs on rust version for dedupe (#2218)
## Description

Quick PR pointing out the correct version of RUST to use with new dedupe
library. Without this on mac-os using `uv run` commands throw the
following error


```bash
ahmed@Ahmeds-MacBook-Pro-3 marin % uv run scripts/ray/cluster.py dashboard
        Built marin-root @ file:///Users/ahmed/code/marin
        Built levanter @ file:///Users/ahmed/code/marin/lib/levanter
        Built fray @ file:///Users/ahmed/code/marin/lib/fray
        Built marin @ file:///Users/ahmed/code/marin/lib/marin
        Built zephyr @ file:///Users/ahmed/code/marin/lib/zephyr
  × Failed to build `dupekit @ file:///Users/ahmed/code/marin/lib/dupekit`
    ├─▶ The build backend returned an error
    ╰─▶ Call to `maturin.build_editable` failed (exit status: 1)

        [stdout]
        Running `maturin pep517 build-wheel -i /Users/ahmed/Library/Caches/uv/builds-
  v0/.tmp0kvfDt/bin/python --compatibility off --editable`

        [stderr]
          Downloaded csv-core v0.1.13
          Downloaded arrow-csv v57.1.0
        error: failed to parse manifest at `/Users/ahmed/.cargo/registry/src/index.crates.io-
  6f17d22bba15001f/arrow-csv-57.1.0/Cargo.toml`

        Caused by:
          feature `edition2024` is required

          The package requires the Cargo feature called `edition2024`, but that feature is not
  stabilized in this version of Cargo (1.80.1 (376290515 2024-07-16)).
          Consider trying a newer version of Cargo (this may require the nightly release).
          See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for
  more information about the status of this feature.
        💥 maturin failed
          Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
          Caused by: `cargo metadata` exited with an error:
        Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/ahmed/Library/Caches/
  uv/builds-v0/.tmp0kvfDt/bin/python', '--compatibility', 'off', '--editable'] returned non-
  zero exit status 1

        hint: This usually indicates a problem with the package or the build environment.
    help: `dupekit` was included because `marin-root` (v0.1.0) depends on `dupekit`
    ```

## Checklist

- [x] You ran `uv run python infra/pre-commit.py --all-files` to lint/format your code
- [x] You ran 'pytest' to test your code