Disable checkpointing as it's broken and threw error
jaxlib._jax.XlaRuntimeError: INTERNAL: Core halted unexpectedly: INTERNAL: Accelerator device halted prematurely, perhaps due to an on-device check-failure. Node 0 halted unexpectedly at tag:pc TensorCoreSequencer:1:0x9e (from TensorCoreSequencer:1:0x1fe): scheckne: