`haliax>=1.4.dev450` (#1278)
Needs
https://github.com/marin-community/haliax/commit/7e96b90f61c252c88f1aa623e43a180782b08762,
otherwise get TPU test failures like [these][gha]:

```
src/levanter/compat/hf_checkpoints.py:924: in save_pretrained
    save_state_dict(shard_numpy, os.path.join(local_path, shard_name))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

state_dict = ***'a_bool_buffer': array([ True, False,  True, False]), 'a_float_param': array([10., 20., 30.], dtype=float32), 'an_int...., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32), ...***
path = '/tmp/tmpoqk9suzp/model.safetensors'

    def save_state_dict(state_dict: StateDict, path):
        """
        Save a model's state dict to a file, bringing all tensors to the CPU first and then converting to numpy.
        This will save using safetensors format
        """
        state_dict = ***k: v for k, v in state_dict.items() if v is not None***
        if jax.process_index() == 0:
            # the "pt" is a lie but it doesn't seem to actually matter and HF demands it
>           safetensors.numpy.save_file(state_dict, path, metadata=***"format": "pt"***)
            ^^^^^^^^^^^^^^^^^
E           AttributeError: module 'safetensors' has no attribute 'numpy'
```

[gha]:
https://github.com/marin-community/levanter/actions/runs/18828420592/job/53715209329#step:8:107