Fix GPU local cluster training (2) (#2116)
## Description

Part of https://github.com/marin-community/marin/issues/1981

This is the second PR that has the proper Haliax fixes by David. The
previous one https://github.com/marin-community/marin/pull/2112 is
closed without merging.
- sniffing available hardware resources in experiment code has also been
removed

I tested GPU training on both Colab and the NLP cluster, with one or
multiple GPUs, and everything seems good so far. Steps:

```
1  git clone https://github.com/marin-community/marin
2  cd marin
3  uv venv --python 3.11
4  . .venv/bin/activate
5  uv sync --all-packages --extra=cuda12
6  export WANDB_API_KEY='...'
7  export HF_TOKEN='...'
8  python -m experiments.speedrun.submission_2071.main --force_run_failed true --dry_run true
```

(or `uvx wandb login`, `uvx hf auth login`)

changes in the PR:
- create resource configs for local ray cluster in Executor
- updated NVTE codepath to use SequenceDescriptor instead of a
materialized mask
```
transformer_engine/jax/attention.py:1189: DeprecationWarning: Pass mask to fused_attn is deprecated, please use SequenceDescriptor instead. See help(transformer_engine.jax.attention.SequenceDescriptor) for details.
```
- misc small fixes (config serialization, etc.)

(lots of commits in this PR mostly because branched off an older branch)

This PR sets up the JAX_FLASH attention backend, and I am pretty sure
NVTE would fail because I ended up reverting setting the global mesh
resource set in `train_lm.py`:

```
AssertionError: Global mesh resource is not set. Please set the MeshResource via a global_shard_guard context. If you are not using multiple GPUs, you can use an empty MeshResource by wrapping your program in 'with global_shard_guard(MeshResource()):'
```

This really should integrate with the TrainerConfig, and I think it is
better for NVTE support & any refactor to be a separate issue. More
recent NVTE versions also need a higher jax(lib) version than 0.6.2.

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: David Hall <david.hall@openathena.ai>